[package]
name = "dot_punk"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.3"
serde = "1.0.228"
ron = "0.11.0"
bevy = "0.16.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
